#!/bin/bash

set -e

APP_SOURCE_ROOT=./deckky.build

msinstall()
{
    ENVIRONMENT=$1
    echo "Installing ${ENVIRONMENT} environment on this machine"

    if hash erl 2>/dev/null; then
      erlver=$(erl -noshell -eval 'io:fwrite("~s\n", [erlang:system_info(otp_release)]).' -s erlang halt)
      echo "Erlang version: ${erlver}"
    else
      echo "Erlang not installed"; exit 1;
    fi

    if hash elixir 2>/dev/null; then
      elixirver=$(elixir -e "IO.puts System.version")
      echo "Elixir installed: ${elixirver}"
    else
      echo "Elixir not installed"; exit 1;
    fi

    rm -rf ${APP_SOURCE_ROOT}

    git clone --depth 1 https://github.com/nicolafiorillo/deckky.git ${APP_SOURCE_ROOT}|| { echo "git failed"; exit 1; }

    cd ${APP_SOURCE_ROOT}

    # Resolving dependencies
    MIX_ENV=${ENVIRONMENT} mix local.hex --force || { echo "getting local.hex failed"; exit 1; }
    MIX_ENV=${ENVIRONMENT} mix local.rebar --force || { echo "getting local.rebar failed"; exit 1; }
    MIX_ENV=${ENVIRONMENT} mix deps.get

#    echo "Generating static manifest..."
#    MIX_ENV=${ENVIRONMENT} mix phx.digest || { echo "mix phx.digest failed"; exit 1; }

    echo "Generating release package..."
    MIX_ENV=${ENVIRONMENT} mix release || { echo "mix release failed"; exit 1; }

    pwd
    mv ./_build/prod/rel/deckky ..
    cd ..
    rm -rf ${APP_SOURCE_ROOT}
    
    echo "Starting Deckky..."
    ./deckky/bin/deckky start

    echo "Deploy done."
}

main() {
    while true; do
        read -p "This will DESTROY the current app and data. Are you sure to install (yN)?" yn
        case $yn in
            [Yy]* ) msinstall $1; break;;
            [Nn]* ) echo "Nothing to do"; exit;;
            * ) echo "Nothing to do"; exit;;
        esac
    done
}

main prod
